=== frac/opentrials/opentrials/repository/xml/reclac.dtd
<!-- ===========================================================================
File: reclac.dtd

RECLAC: Latin-American and Caribbean Clinical Trial Record XML DTD
DTD Version 1.0: 2010-03-01

This DTD depends on the reclac-vocabularies.mod definitions file.

See:
http://reddes.bvsalud.org/projects/clinical-trials/wiki/RegistrationDataModel

Partially based on the WHO ICTRP XML DTD, http://www.who.int/ictrp
DTD Version 1.0: 2008-04-23 (with changes up to and including 2008-09-15)
Most element names are the same. Structure is different, with more validation
in the form of attribute enumerations. Also, this is intended to represent a
single trial record.

Comments:
  - "formset n/9" refer to each of the 9 trial submission forms
  - "TRDS n (x..y)": field number in the ICTRP Trial Registration Data Set
                     (x..y) indicate element multiplicity in UML notation
=========================================================================== -->

<!ENTITY % vocabularies SYSTEM "reclac-vocabularies.mod">
%vocabularies;

<!ELEMENT trial (trial_identification, sponsors_and_support, health_conditions,
          interventions, recruitment, study_type, outcomes, contacts, references?)>
    <!-- trial record must have explicit attribute type="interventional"
         in preparation for eventual support for observational studies -->
    <!ATTLIST trial type (interventional) #REQUIRED>

    <!-- formset 1/9 -->
    <!ELEMENT trial_identification (scientific_title, scientific_acronym?,
                    public_title?, acronym?, utn?, reclac_id?,
                    secondary_ids*)>

    <!ELEMENT scientific_title (#PCDATA)>                       <!--TRDS 10a (1)-->
        <!ATTLIST scientific_title
            lang (%language.options;) #IMPLIED>
    <!ELEMENT scientific_acronym (#PCDATA)>                     <!--TRDS 10b (0..1)-->
        <!ATTLIST scientific_acronym
            lang (%language.options;) #IMPLIED>
    <!ELEMENT public_title (#PCDATA)>                           <!--TRDS 9a (0..1)-->
        <!ATTLIST public_title
            lang (%language.options;) #IMPLIED>
    <!ELEMENT acronym (#PCDATA)>                                <!--TRDS 9b (0..1)-->
        <!ATTLIST acronym
            lang (%language.options;) #IMPLIED>
    <!ELEMENT utn (#PCDATA)>                                    <!--TRDS 3 (0..1)-->
    <!ELEMENT reclac_id (#PCDATA)>                              <!--TRDS 1 (0..1)-->
    <!ELEMENT secondary_ids (secondary_id+)>
        <!ELEMENT secondary_id (sec_id,issuing_authority)>
        <!ELEMENT sec_id (#PCDATA)>                         <!--TRDS 3a (0..*)-->
        <!ELEMENT issuing_authority (#PCDATA)>              <!--TRDS 3b (0..*)-->

    <!-- formset 2/9 -->
    <!ELEMENT sponsors_and_support (primary_sponsor, secondary_sponsor*, source_support*)>
    <!ELEMENT primary_sponsor (name, address?)>                 <!--TRDS 5 (1)-->
        <!ATTLIST primary_sponsor
            country_code (%country.options;) #REQUIRED>
    <!ELEMENT secondary_sponsor (name, address?)>               <!--TRDS 6 (0..*)-->
        <!ATTLIST secondary_sponsor
            country_code (%country.options;) #REQUIRED>
    <!ELEMENT source_support (name, address?)>                  <!--TRDS 4 (0..*)-->
        <!ATTLIST source_support
            country_code (%country.options;) #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT address (#PCDATA)>

    <!-- formset 3/9 -->
    <!ELEMENT health_conditions (freetext?, hc_code*, keyword*)>
        <!ELEMENT freetext (#PCDATA)>                               <!--TRDS 12a, 13a (0..1)-->
            <!ATTLIST freetext
                lang (%language.options;) #IMPLIED>
        <!ELEMENT hc_code (#PCDATA)>                                <!--TRDS 12b (0..*)-->
            <!ATTLIST hc_code
                vocabulary (%vocabulary.options;) #IMPLIED
                version CDATA #IMPLIED>
        <!ELEMENT keyword (#PCDATA)>                                <!--TRDS 12c, 13c (0..*)-->
            <!ATTLIST keyword
                vocabulary (%vocabulary.options;) #IMPLIED
                version CDATA #IMPLIED>

    <!-- formset 4/9 -->
    <!ELEMENT interventions (freetext?, i_code*, keyword*)>           <!--TRDS 12a (0..1)-->
        <!ELEMENT i_code (#PCDATA)>                                   <!--TRDS 12b (0..*)-->
        <!ATTLIST i_code
        value (%interventioncode.options;) #IMPLIED>

    <!-- formset 5/9 -->
    <!ELEMENT recruitment (recruitment_country+,
                           inclusion_criteria, gender?, agemin?, agemax?,
                           exclusion_criteria?,
                           date_enrolment_anticipated?,
                           date_enrolment_actual?,
                           target_size?)>
        <!ATTLIST recruitment
            study_status (%studystatus.options;) #REQUIRED>
    <!ELEMENT recruitment_country EMPTY>                          <!--TRDS 11 (1..*)-->
        <!ATTLIST recruitment_country
            value (%country.options;) #REQUIRED>
    <!ELEMENT inclusion_criteria (#PCDATA)>                       <!--TRDS 14a (1)-->
        <!ATTLIST inclusion_criteria
            lang (%language.options;) #IMPLIED>
    <!ELEMENT gender EMPTY>                                       <!--TRDS 14b (0..1)-->
        <!ATTLIST gender
            value (%gender.options;) #REQUIRED>
    <!ELEMENT agemin (#PCDATA)>                                   <!--TRDS 14c (0..1)-->
        <!ATTLIST agemin
            unit (%ageunit.options;) #REQUIRED>
    <!ELEMENT agemax (#PCDATA)>                                   <!--TRDS 14d (0..1)-->
        <!ATTLIST agemax
            unit (%ageunit.options;) #REQUIRED>
    <!ELEMENT exclusion_criteria (#PCDATA)>                       <!--TRDS 14e (0..1)-->
        <!ATTLIST exclusion_criteria
            lang (%language.options;) #IMPLIED>
    <!ELEMENT date_enrolment_anticipated (#PCDATA)> <!--ISO-8601 date format: YYYY-MM-DD-->
    <!ELEMENT date_enrolment_actual (#PCDATA)>      <!--ISO-8601 date format: YYYY-MM-DD-->
    <!ELEMENT target_size (#PCDATA)>

    <!-- formset 6/9 -->
    <!ELEMENT study_type (study_design, study_endpoint*, phase?)>
        <!ELEMENT study_design (#PCDATA)>
            <!ATTLIST study_design
                lang (%language.options;) #IMPLIED
                expanded_access_program (yes|no) #IMPLIED
                purpose (%purpose.options;) #IMPLIED
                intervention_assignment (%assignment.options;) #IMPLIED
                number_of_arms NMTOKEN #IMPLIED
                masking (%masking.options;) #IMPLIED
                allocation (%allocation.options;) #IMPLIED
            >
        <!ELEMENT study_endpoint EMPTY>                           <!--TRDS 15b (0..1)-->
            <!ATTLIST study_endpoint
                value (%endpoint.options;) #REQUIRED>
        <!ELEMENT phase EMPTY>                                    <!--TRDS 15c (0..1)-->
        <!ATTLIST phase
            value (%phase.options;) #REQUIRED>

    <!-- formset 7/9 -->
    <!ELEMENT outcomes (primary_outcome+, secondary_outcome*)>
    <!ELEMENT primary_outcome (#PCDATA)>
        <!ATTLIST primary_outcome
            lang (%language.options;) #IMPLIED>
    <!ELEMENT secondary_outcome (#PCDATA)>
        <!ATTLIST secondary_outcome
            lang (%language.options;) #IMPLIED>

    <!-- formset 8/9 -->
    <!ELEMENT contacts (public_contact, scientific_contact, site_contact?, person+)>
    <!ELEMENT public_contact EMPTY>
        <!ATTLIST public_contact
            persons IDREFS #REQUIRED>
    <!ELEMENT scientific_contact EMPTY>
        <!ATTLIST scientific_contact
            persons IDREFS #REQUIRED>
    <!ELEMENT site_contact EMPTY>
        <!ATTLIST site_contact
            persons IDREFS #REQUIRED>

    <!ELEMENT person (firstname,middlename?,lastname,address,city,zip,telephone+,email,affiliation)>
        <!ATTLIST person
            pid ID #REQUIRED
            country_code (%country.options;) #REQUIRED>
        <!ELEMENT firstname (#PCDATA)>
        <!ELEMENT middlename (#PCDATA)>
        <!ELEMENT lastname (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT zip (#PCDATA)>
        <!ELEMENT telephone (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT affiliation (#PCDATA)>

    <!-- formset 9/9 -->
    <!ELEMENT references (link*)>
        <!ELEMENT link (#PCDATA)>
        <!ATTLIST link url CDATA #REQUIRED>

=== frac/opentrials/opentrials/repository/xml/sample_1b.xml
<!DOCTYPE trial SYSTEM "reclac.dtd">
<!--a realistic and valid RECLAC trial XML-->
<!--based on data from the ANZCTR trial ACTRN12610000133033-->
<!--source: http://www.anzctr.org.au/trial_view.aspx?ID=335059-->
<trial type="interventional">
    <trial_identification>
  	<!--TRDS 10a (1)-->
        <scientific_title>Behavioral analysis of preterm neonates included in a tactile and kinesthetic stimulation program during hospitalization in preterm neonates</scientific_title>
	<!--TRDS 10b (0-1)-->
        <scientific_acronym>BATIK</scientific_acronym>
	<!--TRDS 9a (0-1)-->
	<public_title>Tactile and kinesthetic stimulation program during hospitalization and behavioral analysis in preterm neonates</public_title>
	<!--TRDS 9b (0-1)-->
        <acronym>TAKS</acronym>
	<!--TRDS 3a/3b (0-1)-->
	<utn>U9999-9999-0102</utn>
	<!--TRDS 1 (0-1)-->
	<reclac_id>RBR-9zz-2bc</reclac_id>
	<secondary_ids>
	    <secondary_id>
		<!--TRDS 3a (0-N)-->
		<sec_id>ACTRN12610000133033</sec_id>
		<!--TRDS 3b (0-N)-->
		<issuing_authority>ANZCTR</issuing_authority>
	    </secondary_id>
	</secondary_ids>
    </trial_identification>
    <sponsors_and_support>
	<!--TRDS 5 (1)-->
	<primary_sponsor country_code="BR">
	    <name>Universidade de São Paulo</name>
	    <address>
		Rua Prof. Mello Moraes, 1721
		Cidade Universitaria
		Sao Paulo, SP, CEP 055508-900
	    </address>
	</primary_sponsor>
	<!--TRDS 6 (0..*)-->
	<secondary_sponsor country_code="BR">
	    <name>Andreia Menandro Ferreira</name>
	    <address>
		Rua Cônego Valadão, 1539, apt 53
		Gopouva,
		Guarulhos, SP, CEP 07040-000
	    </address>
	</secondary_sponsor>
	<!--TRDS 4 (0..*)-->
	<source_support country_code="BR">
	    <name>Conselho Nacional de Desenvolvimento Cientifico e Tecnologico</name>
	    <address>
		SEPN 507 Ed. CNPq - Terreo - Sala 7
		Brasília, DF, CEP 70740-901
	    </address>
	</source_support>
    </sponsors_and_support>
    <health_conditions>
        <!--TRDS 12a (0..1)-->
	<freetext>preterm neonates</freetext>
        <!--TRDS 12b (0..*)-->
	<hc_code vocabulary="decs" version="2009">M01.060.703.520</hc_code>
        <!--TRDS 12c (0..*)-->
	<keyword vocabulary="decs">C13.703.420.491.500</keyword>
    </health_conditions>
    <interventions>
        <!--TRDS 13a (0..1)-->
	<freetext>
	Stable preterm neonates received tactile and kinesthetic stimulation
	during hospitalization; by trained author and mothers. With ligth
	touch and arms and legs mobilization; during 5 to 15 minutes daily,
	since preterm was clinically stable until hospital discharge.
	</freetext>
        <!--TRDS 13b (0..*)-->
	<i_code value="behavioural" />
        <!--TRDS 13c (0..*)-->
	<keyword vocabulary="decs" version="2009">F02.830.816.850</keyword>
    </interventions>
    <recruitment study_status="completed">
        <!--TRDS 11 (1+)-->
        <recruitment_country value="BR" />
        <!--TRDS 14a (1)-->
	<inclusion_criteria>
    	    Stable preterm infants weighing &lt; 2500 grams, with no significant perinatal asphyxia.
	</inclusion_criteria>
        <!--TRDS 14b (0..1)-->
	<gender value="both" />
        <!--TRDS 14c (0..1)-->
	<agemin unit="weeks">31</agemin>
        <!--TRDS 14d (0..1)-->
	<agemax unit="weeks">36</agemax>
        <!--TRDS 14e (0..1)-->
	<exclusion_criteria>
	    Vision and/or hear disfuction; neurological problems; instable preterms; without family autorization.
	</exclusion_criteria>
        <!--TRDS 16 (1)-->
	<date_enrolment_anticipated>2004-10-01</date_enrolment_anticipated>
        <!--TRDS 16 (1)-->
	<date_enrolment_actual>2004-10-01</date_enrolment_actual>
        <!--TRDS 17 (1)-->
	<target_size>32</target_size>
    </recruitment>
    <study_type>
        <!--TRDS 15b (1)-->
        <study_design expanded_access_program="no"
		      purpose="prevention"
		      intervention_assignment="parallel"
		      number_of_arms="2"
		      masking="open"
		      allocation="non-randomized-controlled">
	    Thirty-two clinically stable preterm infants weighing &lt; 2500
	    grams, with no significant perinatal asphyxia, were allocated to
	    two groups: a control group (CG) in which no intervention was made
	    (n=16) and a study group (SG) in which the newborn infants received
	    tactile and kinesthetic stimulation (n=16). Data on the infants’
	    clinical progress were collected from medical charts and behavioral
	    evaluations were carried out using a series of weekly, 8-minute
	    films recorded from study admission until hospital discharge.
	</study_design>
	<study_endpoint value="safety" />
	<study_endpoint value="efficacy" />
	<study_endpoint value="bioequivalence" />
	<study_endpoint value="biodisponibility" />
	<study_endpoint value="pharmacokinetics" />
	<study_endpoint value="pharmacodynamics" />
	<study_endpoint value="pharmacogenetics" />
        <!--TRDS 15c (1)-->
	<phase value="1-2" />
    </study_type>
    <outcomes>
        <!--TRDS 19 (1..*)-->
	<primary_outcome>
	    Predominance of self-regulated behavior in Behavioral Scale
	    (adapted from Neonatal Behavioral Assessment Scale NBAS).
	    Timepoint: every week, at least one week after beggining of
	    stimulation until hospital discharge.
	</primary_outcome>
        <!--TRDS 20 (1..*)-->
	<secondary_outcome>
	    Shorter duration of hospital stay.
	    Timepoint: after hospitalization.
	</secondary_outcome>
    </outcomes>
    <contacts>
        <!--TRDS 7 (1..*)-->
	<public_contact persons="p1"/>
        <!--TRDS 8 (1..*)-->
	<scientific_contact persons="p1"/>
	<person pid="p1" country_code="BR">
	    <firstname>Andreia</firstname>
	    <middlename>Menandro</middlename>
	    <lastname>Ferreira</lastname>
	    <address>
		Rua Cônego Valadão, 1539, apt 53
		Gopouva
	    </address>
	    <city>Guarulhos, SP</city>
	    <zip>07040-000</zip>
	    <telephone>+55 (11) 2422-7034</telephone>
	    <email>andreiamdeia@yahoo.com</email>
	    <affiliation>Universidade de São Paulo</affiliation>
	</person>
    </contacts>
    <references>
	<link url="http://www.anzctr.org.au/trial_view.aspx?ID=335059">
	    Original trial record at ANZCTR
	</link>
    </references>
</trial>

=== frac/opentrials/opentrials/repository/xml/sample_1a.xml
<!DOCTYPE trial SYSTEM "reclac.dtd">
<!--the simplest possible valid RECLAC trial XML-->
<!--based on data from the ANZCTR; trial: ACTRN12610000133033-->
<trial type="interventional">
    <trial_identification>
      	<!--TRDS 10a (1)-->
        <scientific_title>Tactile and kinesthetic stimulation program during hospitalization and behavioral analysis in preterm neonates</scientific_title>
    </trial_identification>
    <sponsors_and_support>
	<!--TRDS 5 (1)-->
	<primary_sponsor country_code="BR">
	    <name>Conselho Nacional de Desenvolvimento Cientifico e Tecnologico</name>
	</primary_sponsor>
    </sponsors_and_support>
    <health_conditions>
	<freetext>preterm neonates</freetext>
    </health_conditions>
    <interventions>
    	<i_code value="behavioural" />
    </interventions>
    <recruitment study_status="completed">
        <recruitment_country value="BR" />
	<inclusion_criteria>
	Stable preterm infants weighing &lt; 2500 grams, with no significant perinatal asphyxia.
	</inclusion_criteria>
    </recruitment>
    <study_type>
        <study_design>
	    Thirty-two clinically stable preterm infants weighing &lt; 2500
	    grams, with no significant perinatal asphyxia, were allocated to
	    two groups: a control group (CG) in which no intervention was made
	    (n=16) and a study group (SG) in which the newborn infants received
	    tactile and kinesthetic stimulation (n=16). Data on the infants’
	    clinical progress were collected from medical charts and behavioral
	    evaluations were carried out using a series of weekly, 8-minute
	    films recorded from study admission until hospital discharge.
	</study_design>
    </study_type>
    <outcomes>
	<primary_outcome>
	    Predominance of self-regulated behavior in Behavioral Scale
	    (adapted from Neonatal Behavioral Assessment Scale NBAS).
	    Timepoint: every week, at least one week after beggining of
	    stimulation until hospital discharge.
	</primary_outcome>
    </outcomes>
    <contacts>
	<public_contact persons="p1"/>
	<scientific_contact persons="p1"/>
	<person pid="p1" country_code="BR">
	    <firstname>Andreia</firstname>
	    <middlename>Menandro</middlename>
	    <lastname>Ferreira</lastname>
	    <address>
		Rua Cônego Valadão, 1539, apt 53
		Gopouva
	    </address>
	    <city>Guarulhos, SP</city>
	    <zip>07040-000</zip>
	    <telephone>+55 (11) 2422-7034</telephone>
	    <email>andreiamdeia@yahoo.com</email>
	    <affiliation>Universidade de São Paulo</affiliation>
	</person>
    </contacts>

</trial>
